import type { Registry } from '../../kernel/registry.js'

/**
 * Legacy no-op kept for compatibility.
 * Accent instructions now live only inside the identity prompt generated by
 * PromptsService, so the standalone <accent> section is intentionally disabled.
 */
export async function buildAccentSection(
  registry: Registry,
): Promise<string> {
  void registry
  return ''
}
